[KK-6] Обновила SignupViewController
startmobile-kz/kurs.kz pull request #12
Opened 2023-07-02 13:05 UTC by abitoffka

2023-07-02 13:13 UTC, abitoffka commented
Извиняюсь, я забыла отдельную ветку для второго таска создать

2023-07-04 04:55 UTC, aitemr commented on kurs.kz/SignUp/SignupViewController.swift
> +              .underlineStyle: NSUnderlineStyle.single.rawValue
! force unwrap очень плохая идея, давай уберем

2023-07-04 04:56 UTC, aitemr commented on kurs.kz/SignUp/SignupViewController.swift
> +class CustomSkyFloatingLabelTextField: SkyFloatingLabelTextField {
лучше вынести в отдельный  файл

2023-07-04 04:56 UTC, aitemr commented on kurs.kz/SignUp/VerificationPageViewController.swift
> +//        @objc private func verifyButtonDidPressed() {
dead code

удаляем комменты

2023-07-04 04:56 UTC, aitemr requested changes
нужны правки

2023-07-04 09:24 UTC, abitoffka commented on kurs.kz/SignUp/SignupViewController.swift
> +              .underlineStyle: NSUnderlineStyle.single.rawValue
Заменила

2023-07-04 09:40 UTC, abitoffka commented on kurs.kz/SignUp/SignupViewController.swift
> +class CustomSkyFloatingLabelTextField: SkyFloatingLabelTextField {
создала отдельный класс

2023-07-04 09:40 UTC, abitoffka commented on kurs.kz/SignUp/VerificationPageViewController.swift
> +//        @objc private func verifyButtonDidPressed() {
удалила dead code

2023-07-04 09:41 UTC, abitoffka commented
> нужны правки

исправила

2023-07-04 10:01 UTC, cheezyde approved these changes
вроде все кул😅 Молодец!

2023-07-05 04:25 UTC, aitemr approved these changes
👍

2023-07-05 07:59 UTC, closed without merging