[KK-8] Создал RegistrationPersonalDataViewController
startmobile-kz/kurs.kz pull request #20
Opened 2023-07-03 08:48 UTC by cheezyde

2023-07-04 04:33 UTC, aitemr commented on kurs.kz/Registration/RegistrationPersonalDataViewController.swift
> +//MARK: - UI
лишний

2023-07-04 04:33 UTC, aitemr commented on kurs.kz/Registration/RegistrationPersonalDataViewController.swift
> +    private let stackView: UIStackView = {
сюда лучше // MARK: - UI

2023-07-04 04:35 UTC, aitemr commented on kurs.kz/Registration/RegistrationPersonalDataViewController.swift
> +    private let placeholderSwitchView: UIView = {
думаю это контайнер лишний

2023-07-04 04:35 UTC, aitemr commented on kurs.kz/Registration/RegistrationPersonalDataViewController.swift
> +        // Do any additional setup after loading the view.
удалить коммент

2023-07-04 04:35 UTC, aitemr commented on kurs.kz/Registration/RegistrationPersonalDataViewController.swift
> +    //MARK: - lifecycle
lifecycle -> Lifecycle

2023-07-04 04:48 UTC, aitemr commented on kurs.kz/Registration/RegistrationPersonalDataViewController.swift
> +    //MARK: - setup views
// MARK: - Setup Views

2023-07-04 04:53 UTC, aitemr commented on kurs.kz/Registration/RegistrationPersonalDataViewController.swift
> +        //putting elements in the stack:
тоже удаляем коммент

2023-07-04 04:54 UTC, aitemr commented on kurs.kz/Registration/RegistrationPersonalDataViewController.swift
> +class PaddedTextField: SkyFloatingLabelTextField {
вынести в отдельный  файл

2023-07-04 04:54 UTC, aitemr requested changes
нужны правки

2023-07-04 09:21 UTC, cheezyde commented
удалил комменты, поправил марки, создал новый файл для класса PaddedTextField, удалил плейсхолдер

2023-07-05 04:24 UTC, aitemr approved these changes

2023-07-05 04:25 UTC, aitemr commented
👍

2023-07-05 05:34 UTC, aitemr approved these changes

2023-07-05 05:43 UTC, closed without merging