Feature/orynbek/kk 13
startmobile-kz/kurs.kz pull request #30
Opened 2023-07-05 19:41 UTC by diarorynbek

2023-07-06 09:15 UTC, aitemr commented on kurs.kz/Assets.xcassets/Mainpage/frame1.imageset/Frame 26567.pdf
нужно поправить название картинки

2023-07-06 09:15 UTC, aitemr commented on kurs.kz/MainPage/MainPageViewController.swift
> +class MainPageViewController: UIViewController {
final

2023-07-06 09:15 UTC, aitemr commented on kurs.kz/MainPage/MainPageViewController.swift
> +  let imageView: UIImageView = {
private let

2023-07-06 09:15 UTC, aitemr commented on kurs.kz/MainPage/MainPageViewController.swift
> +  let label: UILabel = {
titleLabel

2023-07-06 09:17 UTC, aitemr commented
@diarorynbek название pull request кривое 

[KK-13] Сделал экран онбординга

2023-07-06 09:55 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +  let label: UILabel = {
private let label: UILabel = {
?

2023-07-06 09:57 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +  let buttonLogIn: UIButton = {
private let

2023-07-06 09:57 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +  let buttonRegister: UIButton = {
private let

2023-07-06 10:02 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +    button.layer.cornerRadius = 10
это должно быть в viewDidLayoutSubviews()

2023-07-06 10:03 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +    button.layer.cornerRadius = 10
layers поставить в viewDidLayoutSubviews()

2023-07-06 10:03 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +    button.layer.cornerRadius = 10
viewDidLayoutSubviews()

2023-07-06 10:04 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +  let buttonNext: UIButton = {
private

2023-07-06 10:05 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +
space лишний

2023-07-06 10:11 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +    view.addSubview(buttonNext)
подсказали с первого потока, что можно делать так: [imageView, label, buttonLogIn, buttonRegister, buttonNext].forEach {view.addArrangedSubview($0)}
Типа more concise и легче читать

2023-07-06 10:12 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +
спейсы лишние😅

2023-07-06 10:13 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +
//MARK: - Constraints:

2023-07-06 10:13 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +
// MARK: - Setup Views

2023-07-06 10:14 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +
спейсы😅

2023-07-06 10:14 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +
спейс лишний

2023-07-06 10:17 UTC, cheezyde reviewed
много спейсов вроде лишних, подгрузи мб swiftlint? он тебе не даст забилдить если хоть один спейс не там стоит(

2023-07-06 12:40 UTC, abitoffka commented on kurs.kz/MainPage/MainPageViewController.swift
> +  let buttonLogIn: UIButton = {
может лучше loginButton вместо buttonLogin?

2023-07-06 12:41 UTC, abitoffka commented on kurs.kz/MainPage/MainPageViewController.swift
> +    let button = UIButton()
UIButton(type: .system)

2023-07-06 12:41 UTC, abitoffka commented on kurs.kz/MainPage/MainPageViewController.swift
> +    let button = UIButton()
UIButton(type: .system)

2023-07-06 12:42 UTC, abitoffka commented on kurs.kz/MainPage/MainPageViewController.swift
> +    view.backgroundColor = .white
вроде background писать лучше в setupViews

2023-07-06 12:44 UTC, abitoffka commented on kurs.kz/MainPage/MainPageViewController.swift
> +
разве не "// MARK: - Setup Constraints:" ?

2023-07-06 12:44 UTC, abitoffka commented on kurs.kz/MainPage/MainPageViewController.swift
> +  private func setupConstriants() {
setupConstraints

2023-07-06 17:02 UTC, cheezyde commented on kurs.kz/MainPage/MainPageViewController.swift
> +
не знаю, я по своему старому реквесту чекал, мне не правили😅

2023-07-07 04:47 UTC, diarorynbek commented on kurs.kz/MainPage/MainPageViewController.swift
> +class MainPageViewController: UIViewController {
не понял?

2023-07-07 04:53 UTC, diarorynbek commented on kurs.kz/MainPage/MainPageViewController.swift
> +    view.addSubview(buttonNext)
ого. Крутая штука спасибо

2023-07-07 04:59 UTC, diarorynbek commented
Исправил ошибки. Посмотрите

2023-07-07 11:25 UTC, aitemr commented on kurs.kz/MainPage/MainPageViewController.swift
> +  override func viewDidLoad() {
// MARK: - Lifecycle

2023-07-07 11:25 UTC, aitemr commented on kurs.kz/MainPage/MainPageViewController.swift
> +  // MARK: - Setup Constraints:"
лишний :

2023-07-07 11:26 UTC, aitemr commented on kurs.kz/MainPage/MainPageViewController.swift
> +  // MARK: - Setup Views:"
лишний :

2023-07-07 11:26 UTC, aitemr requested changes
нужны правки

2023-07-12 10:46 UTC, merged