[KK-26] создал ToSupportViewController
startmobile-kz/kurs.kz pull request #39
Opened 2023-07-10 04:38 UTC by Askerbekovbekzhan

2023-07-10 06:16 UTC, damiraliyev commented on kurs.kz/ToSupport/ToSupportViewController.swift
> +        view.backgroundColor = .white
Привет! Ислам нас просит ревьюить ваш код тоже. Так что чутка сюда зайду покомментить.

для конфигурации вью у вас есть предназначенная для этого функция -> SetupViews. Лучше поместить туда. в viewDidLoad по сути должны быть только вызовы каких то функции, никакой прямой логики.

2023-07-10 06:16 UTC, damiraliyev commented on kurs.kz/ToSupport/ToSupportViewController.swift
> +        view.backgroundColor = .white
Привет! Ислам нас просит ревьюить ваш код тоже. Так что чутка сюда зайду покомментить.

для конфигурации вью у вас есть предназначенная для этого функция -> SetupViews. Лучше поместить туда. в viewDidLoad по сути должны быть только вызовы каких то функции, никакой прямой логики.

2023-07-10 06:20 UTC, damiraliyev commented on kurs.kz/ToSupport/ToSupportViewController.swift
> +    private func setupView() {
в этой функции может происходить конфигурация нескольких вью, так что лучше метод назвать -> setupViews

2023-07-12 06:00 UTC, aitemr requested changes
нужны правки

2023-07-12 06:00 UTC, aitemr commented on kurs.kz/.DS_Store
cmd shift . в папке и удалим давай

2023-07-12 06:00 UTC, aitemr commented on kurs.kz/Assets.xcassets/ToSupportIcons/telegram_icon.imageset/Contents.json
вечером покажу как картинку добавлять

2023-07-12 06:00 UTC, aitemr commented on kurs.kz/ToSupport/SupportTableViewCell.swift
> +        contentView.addSubview(supportImageView)
нужны метод setupViews & setupConstraints

2023-07-12 06:00 UTC, aitemr commented on kurs.kz/ToSupportViewController.swift
> +class ToSupportViewController: UIViewController {
final

2023-07-12 06:00 UTC, aitemr commented on kurs.kz/ToSupportViewController.swift
> +        view.addSubview(titleLabel)
разделяем методы

2023-07-12 06:00 UTC, aitemr commented on kurs.kz/ToSupportViewController.swift
> +    override func viewDidLoad() {
// MARK: -

2023-07-12 06:00 UTC, aitemr commented on kurs.kz/ToSupportViewController.swift
> +    private let titleLabel: UILabel = {
// MARK:

2023-07-12 06:00 UTC, aitemr commented on kurs.kz/ToSupport/SupportTableViewCell.swift
> +    private let supportImageView: UIImageView = {
// MARK: -

2023-07-12 11:52 UTC, aitemr commented on kurs.kz/ToSupport/SupportTableViewCell.swift
> +    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
// MARK:

2023-07-12 11:52 UTC, aitemr commented on kurs.kz/ToSupport/SupportTableViewCell.swift
> +    func configure(with model: (image: UIImage?, title: String)) {
// MARK: - Public

2023-07-12 11:52 UTC, aitemr commented on kurs.kz/ToSupport/SupportTableViewCell.swift
> +    func configure(with model: (image: UIImage?, title: String)) {
public

2023-07-12 11:55 UTC, aitemr commented on kurs.kz/Assets.xcassets/ToSupportIcons/telegram_icon.imageset/Contents.json
нужны исправить картинки

2023-07-12 11:55 UTC, aitemr requested changes
нужны правки

2023-07-13 04:51 UTC, aitemr approved these changes

2023-07-13 05:40 UTC, merged