[KK-35] Создала ProfileViewController
startmobile-kz/kurs.kz pull request #49
Opened 2023-07-13 20:04 UTC by abitoffka

Ссылка на задачу: https://startmobile.atlassian.net/browse/KK-35?atlOrigin=eyJpIjoiMmVhOTZmZTFmYTE0NDAyYjgwNjIzZmE2Yzk1NTRmYmEiLCJwIjoiaiJ9

2023-07-15 06:12 UTC, cheezyde commented on kurs.kz/Profile/ProfileTableViewCell.swift
> +    var notificationImageView: UIImageView = {
я бы заприватил эту вьюшку и создал бы паблик функцию которая задавала бы нужные пропертис. что-то вроде cell.hideNotification(). Я как раз хотел уточнить на лекции, насколько это плохо - у самого в коде есть пара таких же моментов.

2023-07-15 06:32 UTC, cheezyde commented
Вроде супер кул!

2023-07-18 01:52 UTC, aitemr commented on kurs.kz/Profile/ProfileViewController.swift
> +        informationTableView.layer.cornerRadius = 8
super жок

2023-07-18 01:53 UTC, aitemr commented on kurs.kz/Profile/ProfileViewController.swift
> +        if section == 0 {
давай сделаем лучше enum для секции

2023-07-18 01:53 UTC, aitemr commented on kurs.kz/Profile/ProfileViewController.swift
> +    // swiftlint:enable cyclomatic_complexity
ого

2023-07-18 01:54 UTC, aitemr approved these changes
👍

2023-07-18 01:54 UTC, aitemr requested changes
нужны правки

2023-07-20 10:35 UTC, aitemr approved these changes
👍

2023-07-20 10:37 UTC, merged