[KK-62] добавил нетворкинг в ExchangeListViewController
startmobile-kz/kurs.kz pull request #70
Opened 2023-07-23 08:55 UTC by cheezyde

https://github.com/startmobile-kz/kurs.kz/assets/126853828/e2cc977a-0bba-42d9-afdb-abe311ed4985

2023-07-25 11:21 UTC, aitemr commented on kurs.kz/Currency/Model/CurrencySelectorManager.swift
> +struct CurrencySelectorManager {
CurrencySelectorManager - 
CurrencyListService

2023-07-25 11:23 UTC, aitemr requested changes
убрать manager

2023-07-27 23:27 UTC, cheezyde commented
https://github.com/startmobile-kz/kurs.kz/assets/126853828/663d7b93-7908-4629-86b7-0688b2dddc7e

2023-07-27 23:29 UTC, cheezyde commented
исправил название manager и добавил фильтры

2023-07-28 06:03 UTC, aitemr commented on kurs.kz/.DS_Store
нужно удалить

2023-07-28 06:04 UTC, aitemr commented on kurs.kz/Currency/CurrencySelectorViewController.swift
> +    private var searchArray = [Currency]()
searchArray -> currencies

2023-07-28 06:04 UTC, aitemr commented on kurs.kz/Currency/CurrencySelectorViewController.swift
> +    var currencyManager = CurrencySelectorListService()
перемениовать менеджера

2023-07-28 06:05 UTC, aitemr commented on kurs.kz/Currency/CurrencySelectorViewController.swift
> +        isSearching ? searchArray.count : currenciesArray.count
currenciesArray -> filteredCurrencies

2023-07-28 06:05 UTC, aitemr commented on kurs.kz/MainExchangeList/ExchangeListHeaderView.swift
> +            buyRateFilterButton.setImage(UIImage(named: "down_up_filter"), for: .normal)
appimage

2023-07-28 06:05 UTC, aitemr commented on kurs.kz/MainExchangeList/ExchangeListHeaderView.swift
> +            sellRateFilterButton.setImage(UIImage(named: "up_down_filter"), for: .normal)
appimage

2023-07-28 06:06 UTC, aitemr commented on kurs.kz/MainExchangeList/Model/ExchangerListService.swift
> +    let exchangeListURL = "http://77.240.38.143:4443/actual_currency_rates"
urlcomponent

2023-07-28 06:06 UTC, aitemr requested changes
нужны правки

2023-07-28 06:48 UTC, cheezyde commented on kurs.kz/Currency/CurrencySelectorViewController.swift
> +        isSearching ? searchArray.count : currenciesArray.count
не наоборот? 
currenciesArray -> currencies
searchArray -> filteredCurrencies?

2023-08-04 05:37 UTC, aitemr approved these changes

2023-08-04 05:37 UTC, merged