[KK-54] Сделал Offfer Sended
startmobile-kz/kurs.kz pull request #73
Opened 2023-07-23 14:30 UTC by diarorynbek

Использовал. custom Cell and header
https://github.com/startmobile-kz/kurs.kz/assets/138557924/09f99a20-a298-42d4-aad9-79b4c3880fa1

2023-07-25 11:22 UTC, diarorynbek commented
Решил конфликты

2023-07-25 11:45 UTC, aitemr commented on kurs.kz/OfferSend/SendTalbeVIew.swift
> +class OfferSendedViewController: UIViewController {
final

2023-07-25 11:46 UTC, aitemr commented on kurs.kz/OfferSend/SendTalbeVIew.swift
удалить?

2023-07-25 11:47 UTC, aitemr commented on kurs.kz/OfferSended/OfferSendedViewController.swift
> +        tableView.register(OfferSendedHeader.self, forHeaderFooterViewReuseIdentifier: "header_id")
удалить

2023-07-25 11:47 UTC, aitemr commented on kurs.kz/OfferSended/OfferSendedViewController.swift
> +        view.backgroundColor = AppColor.gray10.uiColor
setupViews

2023-07-25 11:47 UTC, aitemr commented on kurs.kz/OfferSended/OfferSendedViewController.swift
> +        tableView.layer.cornerRadius = 8
viewLayoutSubViews

2023-07-25 11:48 UTC, aitemr commented on kurs.kz/OfferSended/OfferSendedViewController.swift
> +        header.frame = CGRect(x: 0, y: 0, width: 343, height: 53)
UiScreen.main.bounds.width - 32

2023-07-25 11:49 UTC, aitemr commented on kurs.kz/OfferSended/OfferSendedHeader.swift
> +        label.font = .boldSystemFont(ofSize: 16)
AppFont

2023-07-25 11:49 UTC, aitemr requested changes
нужны правки

2023-07-25 12:17 UTC, diarorynbek commented
Поправки сделал

2023-07-26 10:46 UTC, aitemr approved these changes
👍

2023-07-26 10:47 UTC, merged