[85ztn3gzr] добавил alamofire в свои контроллеры, фиксы в контроллерах
startmobile-kz/kurs.kz pull request #84
Opened 2023-07-30 21:40 UTC by cheezyde

фиксы: 

- Починил текстфилды в экране RegistrationPasswordViewController
- Сделал все сортировщики MUX в экране ExchangeListViewController
- Добавил Alamofire в ExchangerListService и CurrencySelectorListService
- Изменил работу Panmodal в CurrencySelectorViewController: меняет высоту в зависимости от нажатий в searchbar
- изменил картинки на AppImage

https://github.com/startmobile-kz/kurs.kz/assets/126853828/4a8e2f8b-1031-4684-a547-10620e5a33d1

2023-08-03 18:54 UTC, aitemr commented on kurs.kz/Currency/Model/CurrencyListService.swift
> +========
после решение конфликтов запуска проект и проверяем

2023-08-03 18:54 UTC, aitemr commented on kurs.kz/Currency/Model/CurrencyListService.swift
> +>>>>>>>> develop:kurs.kz/Currency/Model/CurrencyListService.swift
?

2023-08-03 18:55 UTC, aitemr requested changes
не правильно исправлен конфликт

2023-08-04 04:41 UTC, damiraliyev commented on kurs.kz/Currency/CurrencySelectorViewController.swift
> +    var currencyListService = CurrencySelectorListService()
private

2023-08-04 04:43 UTC, damiraliyev commented on kurs.kz/Currency/CurrencySelectorViewController.swift
> +        currencyListService.fetchCurrencies()
лушче вынести эти подписки на делегаты и запросы в отдельные функции. в viewDidLoad должны быть вызовы функции этого контроллера, чтобы сделать его максимально чистым

2023-08-07 06:19 UTC, damiraliyev commented on kurs.kz/Currency/CurrencySelectorViewController.swift
> +        setUpCurrency()
хорошо исправил👍
Небольшая поправка: setUp -> setup. Ошибка небольшая, просто нужно сохранять постоянство в коде.

2023-08-07 06:21 UTC, damiraliyev commented on kurs.kz/MainExchangeList/ExchangeListTableViewCell.swift
> +    }()
нужен спейс после 55ой строки, потому что между другими свойствами есть спейс, нужно сохранять однообразность

2023-08-08 11:19 UTC, aitemr approved these changes

2023-08-08 11:19 UTC, merged